name: Docker CI/CD Pipeline

on:
  push:
    tags:
      - 'qa/morent-web/*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/qa/morent-web/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push Image
      - name: Build Docker Image
        if: startsWith(github.ref, 'refs/tags/qa/morent-web/')
        run: |
          docker build -t morent-web:latest .
          docker run -d morent-web:latest

      - name: Push Docker Image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/qa/morent-web/')
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/morent-web:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy MorentAPI to server
        if: startsWith(github.ref, 'refs/tags/qa/morent-web/')
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/morent-web:${{ github.sha }}
            sudo docker stop morent-web || true
            sudo docker rm morent-web || true
            sudo docker run -d --name morent-web --network="host" -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/morent-web:${{ github.sha }}